server:
  listen:
    host: "0.0.0.0"
    port: 7900
  tls:
    host: "0.0.0.0"
    port: 7943

log:
  level: warn
  output: stderr

database:
  dsn: "postgres://api7ee:changeme@postgresql:5432/api7ee"

prometheus:
  addr: "http://prometheus:9090"
