{{- define "gvList" -}}
{{- $groupVersions := . -}}

<!-- This document is automatically generated by the 'generate-crd-docs' command of API7 Ingress Controller, please do not edit manually -->

# API7 Ingress Controller API References

This document provides the API resource description for the API7 Ingress Controller.

## Packages
{{- range $groupVersions }}
- {{ markdownRenderGVLink . }}
{{- end }}

{{ range $groupVersions }}
{{ template "gvDetails" . }}
{{ end }}

{{- end -}}
