ARG ENABLE_PROXY=false

FROM node:22 AS node_builder

ARG TARGETARCH
ARG ADC_COMMIT=250cef76fdb76e344bef3f42f85ac46ec71b17c8

WORKDIR /app

RUN apt update \
    && apt install -y git \
    && git clone --branch main https://github.com/api7/adc.git \
    && cd adc \
    && git checkout ${ADC_COMMIT} \
    && corepack enable pnpm \
    && pnpm install \
    && NODE_ENV=production npx nx build cli \
    && node --experimental-sea-config apps/cli/node-sea.json \
    && npx ts-node apps/cli/scripts/download-node.ts \
    && npx postject ./node-binary/linux-${TARGETARCH} NODE_SEA_BLOB sea-prep.blob --sentinel-fuse NODE_SEA_FUSE_fce680ab2cc467b6e072b8b5df1996b2 \
    && mv ./node-binary/linux-${TARGETARCH} /bin/adc \
    && rm -rf /app

FROM golang:1.22 AS builder
WORKDIR /workspace
COPY go.* ./

RUN if [ "$ENABLE_PROXY" = "true" ] ; then go env -w GOPROXY=https://goproxy.cn,direct ; fi \
    && go mod download

COPY . .

RUN --mount=type=cache,target=/root/.cache/go-build make build && mv bin/api7-ingress-controller /bin && rm -rf /workspace

FROM debian:bullseye-slim
WORKDIR /app

COPY --from=builder /bin/api7-ingress-controller .
COPY --from=node_builder /bin/adc /bin/adc
COPY config/samples/config.yaml ./conf/config.yaml

ENTRYPOINT ["/app/api7-ingress-controller"]
CMD ["-c", "/app/conf/config.yaml"]
