ARG ENABLE_PROXY=false
ARG TARGETARCH

FROM golang:1.22 AS builder
WORKDIR /workspace
COPY go.* ./

RUN if [ "$ENABLE_PROXY" = "true" ] ; then go env -w GOPROXY=https://goproxy.cn,direct ; fi \
    && go mod download

COPY . .

RUN --mount=type=cache,target=/root/.cache/go-build make build && mv bin/api7-ingress-controller /bin && rm -rf /workspace

FROM debian:bullseye-slim
WORKDIR /app

COPY --from=builder /bin/api7-ingress-controller .
COPY config/samples/config.yaml ./conf/config.yaml

RUN apt update \
    && apt install -y git nodejs npm wget curl \
    && git clone https://github.com/api7/adc.git \
    && cd adc \
    && npm install -g n \
    && n lts \
    && corepack enable pnpm \
    && pnpm install \
    && npx nx build cli

ENTRYPOINT ["/app/api7-ingress-controller"]
CMD ["-c", "/app/conf/config.yaml"]
