ARG ENABLE_PROXY=false

FROM node:22 AS node_builder

ARG TARGETARCH
ARG ADC_COMMIT=2449ca81e3c61169f8c1e59efb4c1173a766bce2

WORKDIR /app

RUN apt update \
    && apt install -y git \
    && git clone --branch main https://github.com/api7/adc.git \
    && cd adc \
    && git checkout ${ADC_COMMIT} \
    && corepack enable pnpm \
    && pnpm install \
    && NODE_ENV=production npx nx build cli \
    && node --experimental-sea-config apps/cli/node-sea.json \
    && npx ts-node apps/cli/scripts/download-node.ts \
    && npx postject ./node-binary/linux-${TARGETARCH} NODE_SEA_BLOB sea-prep.blob --sentinel-fuse NODE_SEA_FUSE_fce680ab2cc467b6e072b8b5df1996b2 \
    && mv ./node-binary/linux-${TARGETARCH} /bin/adc \
    && rm -rf /app

FROM debian:bullseye-slim

ARG TARGETARCH

WORKDIR /app

COPY --from=node_builder /bin/adc /bin/adc
COPY ./bin/apisix-ingress-controller_${TARGETARCH} ./apisix-ingress-controller
COPY ./config/samples/config.yaml ./conf/config.yaml

ENTRYPOINT ["/app/apisix-ingress-controller"]
CMD ["-c", "/app/conf/config.yaml"]
