apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: httpbin-route
  # namespace: ingress-apisix
spec:
  http:
    - name: route-1
      match:
        paths:
          - /*
      backends:
        - serviceName: httpbin
          servicePort: 80
