apiVersion: apisix.apache.org/v1alpha1
kind: GatewayProxy
metadata:
  name: api7-proxy-config
  namespace: default
spec:
  provider:
    type: ControlPlane
    controlPlane:
      endpoints:
      - ${ADMIN_ENDPOINT}   # https://127.0.0.1:7443
      auth:
        type: AdminKey
        adminKey:
          value: "${ADMIN_KEY}"

---

apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: api7
spec:
  controller: "apisix.apache.org/api7-ingress-controller"
  parameters:
    apiGroup: "apisix.apache.org"
    kind: "GatewayProxy"
    name: "api7-proxy-config"
    namespace: "default"
    scope: "Namespace"

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api7-ingress-tls
spec:
  ingressClassName: api7
  rules:
  - host: httpbin.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: httpbin
            port:
              number: 80
