---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-gateway-networking-k8s-io-v1-gatewayclass
  failurePolicy: Fail
  name: vgatewayclass-v1.kb.io
  rules:
  - apiGroups:
    - gateway.networking.k8s.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - gatewayclasses
  sideEffects: None
