apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-ingress-config
  namespace: {{ .Release.Namespace }}
data:
  config.yaml: |
    log_level: "{{ .Values.logLevel | default "debug" }}"

    controller_name: {{ .Values.controllerName | default "gateway.api7.io/api7-ingress-controller" }}

    leader_election_id: "api7-ingress-controller-leader"
