apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: api7-ingress
    control-plane: controller-manager
  name: {{ .Release.Name }}-metrics-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    control-plane: controller-manager
