# permissions for end users to view gatewayproxies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: gatewayproxy-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: api7-ingress-controller
    app.kubernetes.io/part-of: api7-ingress-controller
    app.kubernetes.io/managed-by: kustomize
  name: gatewayproxy-viewer-role
rules:
- apiGroups:
  - gateway.apisix.io
  resources:
  - gatewayproxies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gateway.apisix.io
  resources:
  - gatewayproxies/status
  verbs:
  - get
