# permissions for end users to edit gatewayproxies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: gatewayproxy-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: api7-ingress-controller
    app.kubernetes.io/part-of: api7-ingress-controller
    app.kubernetes.io/managed-by: kustomize
  name: gatewayproxy-editor-role
rules:
- apiGroups:
  - gateway.apisix.io.github.com
  resources:
  - gatewayproxies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gateway.apisix.io.github.com
  resources:
  - gatewayproxies/status
  verbs:
  - get
