---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: apisix-ingress-manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - namespaces
  - secrets
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apisix.apache.org
  resources:
  - apisixconsumers
  - apisixglobalrules
  - apisixroutes
  - apisixtls
  - apisixupstreams
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apisix.apache.org
  resources:
  - apisixconsumers/finalizers
  - apisixroutes/finalizers
  - apisixtls/finalizers
  - apisixupstreams/finalizers
  verbs:
  - update
- apiGroups:
  - apisix.apache.org
  resources:
  - apisixconsumers/status
  - apisixglobalrules/status
  - apisixroutes/status
  - apisixtls/status
  - apisixupstreams/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apisix.apache.org
  resources:
  - apisixpluginconfigs
  - backendtrafficpolicies
  - consumers
  - gatewayproxies
  - httproutepolicies
  - pluginconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apisix.apache.org
  resources:
  - apisixpluginconfigs/status
  - backendtrafficpolicies/status
  - consumers/status
  - httproutepolicies/status
  verbs:
  - get
  - update
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - discovery.k8s.io
  resources:
  - endpointslices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gateway.networking.k8s.io
  resources:
  - gatewayclasses
  - gateways
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - gateway.networking.k8s.io
  resources:
  - gatewayclasses/status
  - gateways/status
  - httproutes/status
  verbs:
  - get
  - update
- apiGroups:
  - gateway.networking.k8s.io
  resources:
  - httproutes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingressclasses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses/status
  verbs:
  - get
  - update
