log_level: "info"

controller_name: gateway.api7.io/api7-ingress-controller

leader_election_id: "api7-ingress-controller-leader"

control_planes:
  - gateway_name: "api7ee"
    admin_api:
      endpoints:
        - "http://control-plane-1:8080"
      admin_key: "admin-key"

