nameOverride: ""
labelsOverride: {}
annotations: {}
podAnnotations: {}
controllerName: gateway.api7.io/api7-ingress-controller
replicas: 1
admin:
  key: 'a7adm-e8J8XAu6FX3W9LD1f84dg3JCpTIj22e733p5qLZ8NY304ksZIz-1ff6f82c482a41f6b8d86af79d3a1c20' # Pass the admin key generated for the ingress gateway group
  tlsVerify: false
  endpoint: https://api7ee3-dashboard.api7-ee-e2e:7443/apisix/admin
statusAddress: ''
logLevel: debug
nodeSelector: {}
tolerations: []
affinity: {}
podSecurityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
# -- See https://kubernetes.io/docs/tasks/run-application/configure-pdb/ for more details
podDisruptionBudget:
  # -- Enable or disable podDisruptionBudget
  enabled: false
  # -- Set the `minAvailable` of podDisruptionBudget. You can specify only one of `maxUnavailable` and `minAvailable` in a single PodDisruptionBudget.
  # See [Specifying a Disruption Budget for your Application](https://kubernetes.io/docs/tasks/run-application/configure-pdb/#specifying-a-poddisruptionbudget)
  # for more details
  minAvailable: 90%
  # -- Set the maxUnavailable of podDisruptionBudget
  maxUnavailable: 1
# -- Topology Spread Constraints for pod assignment spread across your cluster among failure-domains
# ref: https://kubernetes.io/docs/concepts/workloads/pods/pod-topology-spread-constraints/#spread-constraints-for-pods
topologySpreadConstraints: []
image:
  repository: api7/api7-ingress-controller
  pullPolicy: IfNotPresent
  tag: "dev"
