log_level: "info"                               # The log level of the API7 Ingress Controller.
                                                # the default value is "info".

controller_name: gateway.api7.io/api7-ingress-controller  # The controller name of the API7 Ingress Controller,
                                                          # which is used to identify the controller in the GatewayClass.
                                                          # The default value is "gateway.api7.io/api7-ingress-controller".
leader_election_id: "api7-ingress-controller-leader" # The leader election ID for the API7 Ingress Controller.
                                                        # The default value is "api7-ingress-controller-leader".
leader_election:
  lease_duration: 15s                   # lease_duration is the duration that non-leader candidates will wait
                                        # after observing a leadership renewal until attempting to acquire leadership of a
                                        # leader election.
  renew_deadline: 10s                   # renew_deadline is the time in seconds that the acting controller
                                        # will retry refreshing leadership before giving up.
  retry_period: 2s                      # retry_period is the time in seconds that the acting controller
                                        # will wait between tries of actions with the controller.
  disable: false                        # Whether to disable leader election.

# ingress_class: api7 # The ingress class name of the API7 Ingress Controller.
# ingress_publish_service: "" # The service name of the ingress publish service.
# ingress_status_address: [] # The status address of the ingress.
# gateway_configs:                  # The configuration of the API7 Gateway.
# - name: api7                      # The name of the Gateway in the Gateway API.
#   control_plane:
#     admin_key: "${ADMIN_KEY}"     # The admin key of the control plane.
#     endpoints:         
#       - ${ENDPOINT}               # The endpoint of the control plane.
#     tls_verify: false
#   addresses:                      # record the status address of the gateway-api gateway
#   - "172.18.0.4"                  # The LB IP of the gateway service.
