apiVersion: gateway.apisix.io.github.com/v1alpha1
kind: Guestbook
metadata:
  labels:
    app.kubernetes.io/name: api7-ingress
    app.kubernetes.io/managed-by: kustomize
  name: guestbook-sample
spec:
  # TODO(user): Add fields here
