name: APISIX E2E Test

on:
  push:
    branches:
      - master
      - release-v2-dev
  pull_request:
    branches:
      - master
      - release-v2-dev

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  prepare:
    name: Prepare
    runs-on: buildjet-2vcpu-ubuntu-2204
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go Env
        id: go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"

      - name: Install kind
        run: |
          go install sigs.k8s.io/kind@v0.23.0

  e2e-test:
    needs: 
      - prepare
    runs-on: buildjet-2vcpu-ubuntu-2204
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Go Env
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"

      - name: Build images
        env:
          TAG: dev
          ARCH: amd64
          ENABLE_PROXY: "false"
          BASE_IMAGE_TAG: "debug"
        run: |
          echo "building images..."
          make build-image

      - name: Launch Kind Cluster
        run: |
          make kind-up

      - name: Install Gateway API And CRDs
        run: |
          make install

      - name: Run E2E test suite
        shell: bash
        run: |
          make e2e-test-standalone
