name: E2E Test

on:
  push:
    branches:
      - master
      - release-v2-dev
  pull_request:
    branches:
      - master
      - release-v2-dev

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  prepare:
    name: Prepare
    runs-on: buildjet-2vcpu-ubuntu-2204
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go Env
        id: go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"

      - name: Install kind
        run: |
          go install sigs.k8s.io/kind@v0.23.0

      - name: Install Helm
        run: |
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
          chmod 700 get_helm.sh
          ./get_helm.sh

  e2e-test:
    needs: 
      - prepare
    runs-on: buildjet-2vcpu-ubuntu-2204
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Go Env
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"

      - name: Login to Private Registry
        uses: docker/login-action@v1
        with:
          registry: hkccr.ccs.tencentyun.com
          username: ${{ secrets.PRIVATE_DOCKER_USERNAME }}
          password: ${{ secrets.PRIVATE_DOCKER_PASSWORD }}

      - name: Build images
        env:
          TAG: dev
          ARCH: amd64
          ENABLE_PROXY: "false"
          BASE_IMAGE_TAG: "debug"
        run: |
          echo "building images..."
          make build-image

      - name: Extract adc binary
        run: |
          echo "Extracting adc binary..."
          docker create --name adc-temp api7/api7-ingress-controller:dev
          docker cp adc-temp:/bin/adc /usr/local/bin/adc
          docker rm adc-temp
          chmod +x /usr/local/bin/adc
          echo "ADC binary extracted to /usr/local/bin/adc"

      - name: Launch Kind Cluster
        run: |
          make kind-up

      - name: Install Gateway API And CRDs
        run: |
          make install

      - name: Download API7EE3 Chart
        run: |
          make download-api7ee3-chart

      - name: Loading Docker Image to Kind Cluster
        run: |
          make kind-load-images

      - name: Run E2E test suite
        shell: bash
        env:
          API7_EE_LICENSE: ${{ secrets.API7_EE_LICENSE }}
        run: |
          make e2e-test
