name: push on dockerhub
on: 
  release:
    types: [published]
  push:
    branches:
    - release-v2-dev
    - chore/helm
  workflow_dispatch:
jobs:
  docker:
    runs-on: buildjet-2vcpu-ubuntu-2204
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup Go Env
      uses: actions/setup-go@v4
      with:
        go-version: "1.22"

    - name: Login to Registry
      uses: docker/login-action@v1
      with:
        registry: ${{ secrets.DOCKER_REGISTRY }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build push image
      env:
        TAG: dev
        ARCH: amd64
        ENABLE_PROXY: "false"
        BASE_IMAGE_TAG: "debug"
      run: |
        echo "building images..."
        make build-push-multi-arch-image
